In [1]:
import pandas as pd
import numpy as np

In [3]:
import os 
os.chdir('C:\\Users\\shing\\anaconda_projects\\music re ml project')
import Recommenders as Recommender

In [9]:

song_df_1 = pd.read_csv('triplets_file.csv')
print (song_df_1.shape)
print (song_df_1.head())

(2000000, 3)
                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [10]:
song_df_2 = pd.read_csv('song_data.csv')
print (song_df_2.shape)
display  (song_df_2.head())

(1000000, 5)

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [12]:
song_df_2

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0
...,...,...,...,...,...
999995,SOTXAME12AB018F136,O Samba Da Vida,Pacha V.I.P.,Kiko Navarro,0
999996,SOXQYIQ12A8C137FBB,Jago Chhadeo,Naale Baba Lassi Pee Gya,Kuldeep Manak,0
999997,SOHODZI12A8C137BB3,Novemba,Dub_Connected: electronic music,Gabriel Le Mar,0
999998,SOLXGOR12A81C21EB7,Faraday,The Trance Collection Vol. 2,Elude,0
999999,SOWXJXQ12AB0189F43,Fernweh feat. Sektion Kuchikäschtli,So Oder So,Texta,2004

In [13]:
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on='song_id', how='left')
display (song_df.shape)
display (song_df.head())

(2000000, 7)

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [14]:
print(len(song_df_1), len(song_df_2))

2000000 1000000

In [15]:
len(song_df)

2000000

In [16]:
song_df = song_df.head(50000)
song_df.shape

(50000, 7)

In [17]:
song_df['song'] = song_df['title']+' - '+song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly - Foo Fighters

In [18]:
song_grouped = song_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

                                                song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...             1
1                           #40 - DAVE MATTHEWS BAND             7
2                                & Down - Boys Noize            13
3                          ' Cello Song - Nick Drake             3
4                        '97 Bonnie & Clyde - Eminem             5

In [19]:
grouped_sum = song_grouped['listen_count'].sum()
grouped_sum

np.int64(50000)

In [20]:
song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

,song,listen_count,percentage
6682,Sehr kosmisch - Harmonia,204,0.408
8509,Undo - Björk,182,0.364
1936,Dog Days Are Over (Radio Edit) - Florence + Th...,173,0.346
9256,You're The One - Dwight Yoakam,169,0.338
6348,Revelry - Kings Of Leon,166,0.332
...,...,...,...
9290,Your Time Has Come - Audioslave,1,0.002
9300,Zebra (full-length/album version) - John Butle...,1,0.002
9311,clouding - Four Tet,1,0.002
9312,high fives - Four Tet,1,0.002
9321,the Love Song - K-OS,1,0.002

In [28]:
import Recommenders
pr = Recommenders.popularity_recommender_py()

In [29]:
pr = Recommenders.popularity_recommender_py()
pr.create(song_df, 'user_id', 'song')

In [30]:
pr.recommend(song_df['user_id'][5])

,user_id,song,score,Rank
6682,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sehr kosmisch - Harmonia,204,1.0
8509,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo - Björk,182,2.0
1936,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit) - Florence + Th...,173,3.0
9256,b80344d063b5ccb3212f76538f3d9e43d87dca9e,You're The One - Dwight Yoakam,169,4.0
6348,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Revelry - Kings Of Leon,166,5.0
6671,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Secrets - OneRepublic,158,6.0
3372,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Horn Concerto No. 4 in E flat K495: II. Romanc...,134,7.0
2532,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Fireflies - Charttraxx Karaoke,128,8.0
8287,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Tive Sim - Cartola,117,9.0
3254,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Hey_ Soul Sister - Train,109,10.0

In [32]:
ir = Recommenders.item_similarity_recommender_py()

In [37]:
ir.create(song_df, 'user_id', 'song')

In [38]:
ir.recommend(song_df['user_id'][100])

No. of unique songs for the user: 25
no. of unique songs in the training set: 9325
Non zero values in cooccurence_matrix :47254

,user_id,song,score,rank
0,e006b1a48f466bf59feefed32bec6494495a4436,Lucky (Album Version) - Jason Mraz & Colbie Ca...,0.099839,1
1,e006b1a48f466bf59feefed32bec6494495a4436,Pursuit Of Happiness (nightmare) - Kid Cudi / ...,0.097587,2
2,e006b1a48f466bf59feefed32bec6494495a4436,Somebody To Love - Justin Bieber,0.089141,3
3,e006b1a48f466bf59feefed32bec6494495a4436,Heartbreak Warfare - John Mayer,0.089083,4
4,e006b1a48f466bf59feefed32bec6494495a4436,The Scientist - Coldplay,0.084114,5
5,e006b1a48f466bf59feefed32bec6494495a4436,Alejandro - Lady GaGa,0.080468,6
6,e006b1a48f466bf59feefed32bec6494495a4436,Love Story - Taylor Swift,0.080250,7
7,e006b1a48f466bf59feefed32bec6494495a4436,Bleed It Out [Live At Milton Keynes] - Linkin ...,0.079964,8
8,e006b1a48f466bf59feefed32bec6494495a4436,The Only Exception (Album Version) - Paramore,0.077258,9
9,e006b1a48f466bf59feefed32bec6494495a4436,Billionaire [feat. Bruno Mars] (Explicit Albu...,0.073895,10

In [ ]:
ir.get_similar_items(['Use Somebody - Kings Of Leon'])

no. of unique songs in the training set: 9325